options:
  dynamicSubstitutions: true
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "asia-northeast3"
  _ENVIRONMENT: "dev"
  _MODE: "production"
  _IMAGE: "web-${_ENVIRONMENT}"
  _SERVICE: "${_ENVIRONMENT}-plott-life-web"
  _IMAGE_NAME: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/plott-life-frontend/${_IMAGE}"
  _ASSETS_BUCKET: "${_ENVIRONMENT}-plott-life-assets"

steps:
  - id: "Build Docker image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "build"
      - "-t"
      - "${_IMAGE_NAME}:latest"
      - "-t"
      - "${_IMAGE_NAME}:${SHORT_SHA}"
      - "-f"
      - "apps/web/Dockerfile"
      - .

  - id: "Push to Artifact Registry"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "push"
      - "${_IMAGE_NAME}"
      - "--all-tags"

  - id: "Extract assets from Docker image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "create"
      - "--name"
      - "assets-container"
      - "${_IMAGE_NAME}:latest"

  - id: "Copy assets from container"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "cp"
      - "assets-container:/app/apps/web/dist/client/."
      - "/workspace/assets/"

  - id: "Remove temporary container"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - "rm"
      - "assets-container"

  - id: "Upload assets to GCS bucket"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gsutil"
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "/workspace/assets"
      - "gs://${_ASSETS_BUCKET}"

  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_IMAGE_NAME}:latest"
      - "--labels=repo=${REPO_NAME},commit=${SHORT_SHA},build_id=${BUILD_ID}"
